package probandohibernate;
// Generated 22-ene-2019 12:17:45 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Criaturitas generated by hbm2java
 */
@Entity
@Table(name="Criaturitas"
    ,schema="dbo"
    ,catalog="Ejemplos"
)
public class Criaturitas  implements java.io.Serializable {

     @Id 

    //@GeneratedValue

    @Column(name="ID", unique=true, nullable=false)
     private byte id;
     
         @Column(name="Nombre")
     private String nombre;

    public Criaturitas() {
    }

	
    public Criaturitas(byte id) {
        this.id = id;
    }
    public Criaturitas(byte id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   

    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


